
export const FETCH_STORED_CONTACTS = 'GET_STORED_CONTACTS'
export const FETCH_MORE_CONTACTS = 'GET_MORE_CONTACTS'
export const SEARCH_CONTACTS = 'SEARCH_CONTACTS'
export const SET_SEARCH_CONTACTS = 'SET_SEARCH_CONTACTS'


export const FETCH_STORED_CONTACTS_SUCCEEDED = 'FETCH_STORED_CONTACTS_SUCCEEDED'
export const FETCH_STORED_CONTACTS_FAILED = 'FETCH_STORED_CONTACTS_FAILED'

export const FETCH_MORE_CONTACTS_SUCCEEDED = 'FETCH_MORE_CONTACTS_SUCCEEDED'
export const FETCH_MORE_CONTACTS_FAILED = 'FETCH_MORE_CONTACTS_FAILED'